id: PA311F1F4
initial_creation_type: input
source_metadata:
  title: 'BA: Proto-BA (Buddhanāmanirdeśa)'
  language: zh
  volumes:
    b87161acbf6b485dbe200dd44ca35991:
      title: 'Chapter I: Nidāna'
      base_file: 'Chapter I: Nidāna.txt'
      work_id: W24A6B88F
    1756ac34d7e44ce2a211f066ffa9f1b3:
      title: 'Chapter II: Praṇidhānacaryā'
      base_file: 'Chapter II: Praṇidhānacaryā.txt'
      work_id: W344B4C4E
    06b8e5c6263e44c68d63fa8776944b43:
      title: Title
      base_file: Title.txt
      work_id: W45828492
  chapter_to_tile: {}
created_at: '2022-03-01T21:20:13.556658'
last_modified_at: '2022-03-01T21:20:13.556681'
